# Generated by Django 4.2.28 on 2026-03-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_price_adjustment_percentage'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único da conversa', max_length=100, unique=True, verbose_name='ID da Sessão')),
                ('conversation_type', models.CharField(choices=[('status_inquiry', 'Consulta de Status'), ('scheduling', 'Agendamento'), ('pricing', 'Orçamento'), ('technical_support', 'Suporte Técnico'), ('general_info', 'Informações Gerais'), ('complaint', 'Reclamação')], default='general_info', max_length=30, verbose_name='Tipo de Conversa')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('resolved', 'Resolvida'), ('escalated', 'Escalada'), ('abandoned', 'Abandonada')], default='active', max_length=20, verbose_name='Status')),
                ('client_phone', models.CharField(blank=True, help_text='Telefone para identificação', max_length=20, verbose_name='Telefone do Cliente')),
                ('client_email', models.EmailField(blank=True, help_text='Email para identificação', max_length=254, verbose_name='Email do Cliente')),
                ('context_data', models.JSONField(default=dict, help_text='Informações coletadas durante a conversa', verbose_name='Dados de Contexto')),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='Avaliação do cliente (1-5)', null=True, verbose_name='Score de Satisfação')),
                ('escalation_reason', models.TextField(blank=True, help_text='Por que foi escalado para atendimento humano', verbose_name='Motivo da Escalação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_conversations', to='clients.client', verbose_name='Cliente')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Escalado para')),
            ],
            options={
                'verbose_name': 'Conversa do Chatbot',
                'verbose_name_plural': 'Conversas do Chatbot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Número do Ticket')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Andamento'), ('waiting_client', 'Aguardando Cliente'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='open', max_length=20, verbose_name='Status')),
                ('auto_generated', models.BooleanField(default=True, verbose_name='Gerado Automaticamente')),
                ('ai_analysis', models.JSONField(default=dict, help_text='Análise automática do problema', verbose_name='Análise da IA')),
                ('suggested_solutions', models.JSONField(default=list, help_text='Soluções sugeridas pela IA', verbose_name='Soluções Sugeridas')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='clients.client', verbose_name='Cliente')),
                ('related_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='automated_support.chatbotconversation', verbose_name='Conversa Relacionada')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='jobs.job', verbose_name='Trabalho Relacionado')),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_type', models.CharField(choices=[('consultation', 'Consulta'), ('delivery', 'Entrega'), ('fitting', 'Prova'), ('follow_up', 'Acompanhamento'), ('maintenance', 'Manutenção')], max_length=20, verbose_name='Tipo de Agendamento')),
                ('suggested_datetime', models.DateTimeField(help_text='Data e hora sugeridas pelo sistema', verbose_name='Data/Hora Sugerida')),
                ('alternative_datetimes', models.JSONField(default=list, help_text='Outras opções de data/hora', verbose_name='Alternativas')),
                ('status', models.CharField(choices=[('suggested', 'Sugerido'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Concluído'), ('rescheduled', 'Reagendado')], default='suggested', max_length=20, verbose_name='Status')),
                ('ai_reasoning', models.TextField(help_text='Por que esta data/hora foi sugerida', verbose_name='Raciocínio da IA')),
                ('confidence_score', models.FloatField(help_text='Confiança na sugestão (0-1)', verbose_name='Score de Confiança')),
                ('client_preferences', models.JSONField(default=dict, help_text='Preferências identificadas do cliente', verbose_name='Preferências do Cliente')),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Confirmada')),
                ('confirmation_method', models.CharField(blank=True, choices=[('chatbot', 'Chatbot'), ('phone', 'Telefone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], max_length=20, verbose_name='Método de Confirmação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_schedules', to='clients.client', verbose_name='Cliente')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_schedules', to='jobs.job', verbose_name='Trabalho Relacionado')),
            ],
            options={
                'verbose_name': 'Agendamento Inteligente',
                'verbose_name_plural': 'Agendamentos Inteligentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('bot', 'Bot'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo de Mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('intent_detected', models.CharField(blank=True, help_text='Intenção identificada pelo NLP', max_length=100, verbose_name='Intenção Detectada')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confiança na detecção da intenção (0-1)', null=True, verbose_name='Score de Confiança')),
                ('entities_extracted', models.JSONField(default=dict, help_text='Entidades identificadas na mensagem', verbose_name='Entidades Extraídas')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Tempo para gerar resposta', null=True, verbose_name='Tempo de Resposta (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='automated_support.chatbotconversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Mensagem do Chatbot',
                'verbose_name_plural': 'Mensagens do Chatbot',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(choices=[('status_response', 'Resposta de Status'), ('pricing_info', 'Informação de Preço'), ('scheduling_info', 'Informação de Agendamento'), ('technical_info', 'Informação Técnica'), ('general_info', 'Informação Geral'), ('error_handling', 'Tratamento de Erro')], max_length=30, verbose_name='Categoria')),
                ('trigger_keywords', models.JSONField(default=list, help_text='Palavras que ativam este template', verbose_name='Palavras-chave de Ativação')),
                ('intent_patterns', models.JSONField(default=list, help_text='Padrões regex para detectar intenção', verbose_name='Padrões de Intenção')),
                ('template_content', models.TextField(help_text='Template com variáveis {variavel}', verbose_name='Conteúdo do Template')),
                ('required_context', models.JSONField(default=list, help_text='Dados necessários para usar o template', verbose_name='Contexto Necessário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('priority', models.IntegerField(default=0, help_text='Maior número = maior prioridade', verbose_name='Prioridade')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Contagem de Uso')),
                ('success_rate', models.FloatField(default=0.0, help_text='Taxa de respostas bem-sucedidas', verbose_name='Taxa de Sucesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fallback_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automated_support.autoresponsetemplate', verbose_name='Template de Fallback')),
            ],
            options={
                'verbose_name': 'Template de Resposta Automática',
                'verbose_name_plural': 'Templates de Resposta Automática',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('job_status_update', 'Atualização de Status'), ('delivery_reminder', 'Lembrete de Entrega'), ('payment_reminder', 'Lembrete de Pagamento'), ('appointment_reminder', 'Lembrete de Consulta'), ('quality_feedback', 'Feedback de Qualidade'), ('promotional', 'Promocional'), ('maintenance_alert', 'Alerta de Manutenção')], max_length=30, verbose_name='Tipo de Notificação')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('in_app', 'No App')], max_length=20, verbose_name='Canal')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('personalization_data', models.JSONField(default=dict, help_text='Dados usados para personalizar a mensagem', verbose_name='Dados de Personalização')),
                ('scheduled_for', models.DateTimeField(help_text='Quando a notificação deve ser enviada', verbose_name='Agendado para')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('error_message', models.TextField(blank=True, help_text='Detalhes do erro se falhou', verbose_name='Mensagem de Erro')),
                ('engagement_data', models.JSONField(default=dict, help_text='Dados sobre abertura, cliques, etc.', verbose_name='Dados de Engajamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('recipient_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_notifications', to='clients.client', verbose_name='Cliente Destinatário')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_notifications', to='jobs.job', verbose_name='Trabalho Relacionado')),
            ],
            options={
                'verbose_name': 'Notificação Automatizada',
                'verbose_name_plural': 'Notificações Automatizadas',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
