sonar.projectKey=proteticflow
sonar.organization=your-org-name
sonar.sources=labmanager_source,frontend/labmanager-frontend/src
sonar.python.version=3
sonar.javascript.lcov.reportPaths=frontend/labmanager-frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/node_modules/**,**/venv/**,**/tests/**
