# Generated by Django 4.2.28 on 2026-03-10 19:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('materials', '__first__'),
        ('clients', '0002_client_price_adjustment_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200, verbose_name='Laboratory Name')),
                ('logo', models.ImageField(blank=True, help_text='Logo to be used in reports and documents', null=True, upload_to='lab_logos/', verbose_name='Logo')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('report_header_text', models.TextField(blank=True, help_text='Custom text to appear in report headers', verbose_name='Report Header Text')),
                ('report_footer_text', models.TextField(blank=True, help_text='Custom text to appear in report footers', verbose_name='Report Footer Text')),
                ('primary_color', models.CharField(default='#2563eb', help_text='Hex color code for primary brand color', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#64748b', help_text='Hex color code for secondary brand color', max_length=7, verbose_name='Secondary Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Laboratory Settings',
                'verbose_name_plural': 'Laboratory Settings',
            },
        ),
        migrations.CreateModel(
            name='FinancialClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_type', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('by_job', 'By Completed Job')], max_length=20, verbose_name='Closing Type')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Revenue')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='Total Jobs')),
                ('total_clients', models.IntegerField(default=0, verbose_name='Total Clients')),
                ('breakdown_data', models.JSONField(default=dict, help_text='Detailed breakdown of revenue by client, job type, etc.', verbose_name='Breakdown Data')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Financial Closing',
                'verbose_name_plural': 'Financial Closings',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Delivery Date')),
                ('route_name', models.CharField(blank=True, max_length=100, verbose_name='Route Name')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Driver Name')),
                ('vehicle_info', models.CharField(blank=True, max_length=100, verbose_name='Vehicle Info')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed Delivery')], default='scheduled', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('jobs', models.ManyToManyField(related_name='delivery_schedules', to='jobs.job', verbose_name='Jobs')),
            ],
            options={
                'verbose_name': 'Delivery Schedule',
                'verbose_name_plural': 'Delivery Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('adjusted_amount', models.DecimalField(decimal_places=2, help_text='Amount after client-specific percentage adjustment', max_digits=10, verbose_name='Adjusted Amount')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='clients.client', verbose_name='Client')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Accounts Receivable',
                'verbose_name_plural': 'Accounts Receivable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('issue_date', models.DateField(default=django.db.models.functions.datetime.Now, verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountspayable', to='materials.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Accounts Payable',
                'verbose_name_plural': 'Accounts Payable',
                'ordering': ['-due_date'],
            },
        ),
    ]
