# Generated by Django 4.2.28 on 2026-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='printer_api_port',
            field=models.IntegerField(default=80, verbose_name='Porta da API da Impressora'),
        ),
        migrations.AddField(
            model_name='labsettings',
            name='printer_ip',
            field=models.CharField(blank=True, help_text='IP ou hostname da impressora 3D para envio automático de STL', max_length=50, verbose_name='IP da Impressora 3D'),
        ),
    ]
