# Generated by Django 5.2.1 on 2025-06-02 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the workflow', verbose_name='Order')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Job Stage',
                'verbose_name_plural': 'Job Stages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique identifier for the job', max_length=50, unique=True, verbose_name='Order Number')),
                ('patient_name', models.CharField(blank=True, max_length=255, verbose_name='Patient Name/ID')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Entry Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('status', models.CharField(choices=[('REC', 'Received'), ('PROD', 'In Production'), ('QC', 'Quality Check'), ('COMP', 'Completed'), ('DEL', 'Delivered'), ('CANC', 'Canceled')], default='REC', max_length=4, verbose_name='Status')),
                ('prosthesis_type', models.CharField(blank=True, max_length=100, verbose_name='Prosthesis Type')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('instructions', models.TextField(blank=True, verbose_name='Specific Instructions')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated automatically from items', max_digits=12, null=True, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-entry_date', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price at Order')),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Total Item Price')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_items', to='jobs.job', verbose_name='Job')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_items', to='pricing.serviceitem', verbose_name='Service Item')),
            ],
            options={
                'verbose_name': 'Job Item',
                'verbose_name_plural': 'Job Items',
                'unique_together': {('job', 'service_item')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='items',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobItem', to='pricing.serviceitem', verbose_name='Items'),
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='job_photos/%Y/%m/%d/', verbose_name='Image File')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jobs.job', verbose_name='Job')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstage', verbose_name='Stage When Taken')),
            ],
            options={
                'verbose_name': 'Job Photo',
                'verbose_name_plural': 'Job Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('event_type', models.CharField(choices=[('CREATE', 'Creation'), ('STATUS', 'Status Change'), ('STAGE', 'Stage Change'), ('NOTE', 'Note Added'), ('UPDATE', 'Job Updated')], max_length=10, verbose_name='Event Type')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='jobs.job', verbose_name='Job')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobstage', verbose_name='Associated Stage')),
            ],
            options={
                'verbose_name': 'Job Log',
                'verbose_name_plural': 'Job Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_jobs', to='jobs.jobstage', verbose_name='Current Stage'),
        ),
    ]
