# Generated by Django 4.2.28 on 2026-03-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrador'), ('gerente', 'Gerente'), ('producao', 'Linha de Produção'), ('recepcao', 'Recepção'), ('contabil', 'Contábil')], default='producao', help_text='Define o nível de acesso e o papel do usuário no sistema', max_length=20, verbose_name='Papel do Usuário'),
        ),
    ]
