# Generated by Django 4.2.28 on 2026-03-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_user_type_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_two_factor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Verdadeiro se o usuário escaneou o QR e validou o primeiro token",
                verbose_name="2FA Ativado",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Chave TOTP secreta gerada pelo pyotp",
                max_length=32,
                verbose_name="2FA Secret",
            ),
        ),
    ]
