# Generated by Django 4.2.28 on 2026-03-14 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_price_adjustment_percentage'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('order_code', models.CharField(blank=True, max_length=50, verbose_name='Order Code')),
                ('scanner_brand', models.CharField(choices=[('itero', 'iTero'), ('medit', 'Medit'), ('3shape', '3Shape'), ('carestream', 'Carestream'), ('other', 'Outro')], default='itero', max_length=20, verbose_name='Scanner')),
                ('doctor_name', models.CharField(max_length=200, verbose_name='Dentista')),
                ('doctor_license', models.CharField(blank=True, max_length=50, verbose_name='CRO')),
                ('patient_name', models.CharField(max_length=200, verbose_name='Paciente')),
                ('procedure', models.CharField(blank=True, max_length=200, verbose_name='Procedimento')),
                ('scan_date', models.DateField(blank=True, null=True, verbose_name='Data do Scan')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('ship_to_address', models.TextField(blank=True, verbose_name='Endereço de Envio')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='scans/xml/', verbose_name='Arquivo XML')),
                ('stl_upper', models.FileField(blank=True, null=True, upload_to='scans/stl/', verbose_name='STL Superior')),
                ('stl_lower', models.FileField(blank=True, null=True, upload_to='scans/stl/', verbose_name='STL Inferior')),
                ('gallery_image', models.ImageField(blank=True, null=True, upload_to='scans/gallery/', verbose_name='Galeria')),
                ('print_status', models.CharField(choices=[('pending', 'Aguardando'), ('sent', 'Enviado'), ('printing', 'Imprimindo'), ('done', 'Concluído'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status Impressão')),
                ('print_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado para impressora em')),
                ('raw_metadata', models.JSONField(default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='clients.client', verbose_name='Cliente')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='jobs.job', verbose_name='Trabalho')),
            ],
            options={
                'verbose_name': 'Scan 3D',
                'verbose_name_plural': 'Scans 3D',
                'ordering': ['-created_at'],
            },
        ),
    ]
