# Generated by Django 5.2.3 on 2025-06-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('EXPIRED', 'Expirada'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('current_clients_count', models.IntegerField(default=0)),
                ('current_jobs_this_month', models.IntegerField(default=0)),
                ('current_price_tables_count', models.IntegerField(default=0)),
                ('current_users_count', models.IntegerField(default=1)),
                ('installation_id', models.CharField(blank=True, max_length=64)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('system_info', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicensePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Gratuito'), ('BASIC', 'Básico'), ('PREMIUM', 'Premium')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_clients', models.IntegerField(blank=True, help_text='NULL = ilimitado', null=True)),
                ('max_jobs_per_month', models.IntegerField(blank=True, help_text='NULL = ilimitado', null=True)),
                ('max_price_tables', models.IntegerField(blank=True, help_text='NULL = ilimitado', null=True)),
                ('max_users', models.IntegerField(default=1)),
                ('has_advanced_reports', models.BooleanField(default=False)),
                ('has_client_portal', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='LicenseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('is_valid', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='licensing.license')),
            ],
            options={
                'ordering': ['-check_time'],
            },
        ),
        migrations.AddField(
            model_name='license',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licensing.licenseplan'),
        ),
    ]
