from django.test import TestCase
from django.urls import reverse
from rest_framework.test import APIClient
from rest_framework import status
from datetime import date
from accounts.models import CustomUser
from apps.employees.models import EmployeeProfile, JobAssignment
from apps.jobs.models import Job, JobStage
from apps.clients.models import Client
from apps.financial.models import DeliverySchedule

class EmployeeRBACViewSetTestCase(TestCase):
    def setUp(self):
        self.client_api = APIClient()

        # Criação de usuários com diferentes roles
        self.superadmin = CustomUser.objects.create_user(
            username='admin', password='123', role=CustomUser.UserRole.SUPERADMIN
        )
        self.gerente = CustomUser.objects.create_user(
            username='gerente', password='123', role=CustomUser.UserRole.GERENTE
        )
        self.recepcao = CustomUser.objects.create_user(
            username='recepcao', password='123', role=CustomUser.UserRole.RECEPCAO
        )
        self.producao = CustomUser.objects.create_user(
            username='producao', password='123', role=CustomUser.UserRole.PRODUCAO
        )

        # Dados base
        self.employee_gerente = EmployeeProfile.objects.create(
            user=self.gerente, name='Gerente Teste', document_number='11122233344',
            department='Administração', position='Gerente Geral', hire_date=date.today()
        )
        self.employee_producao = EmployeeProfile.objects.create(
            user=self.producao, name='Producao Teste', document_number='55566677788',
            department='Cerâmica', position='Ceramista', hire_date=date.today()
        )
        
        # Cliente para Jobs
        self.client_obj = Client.objects.create(
            name='Clinica Teste', document_number='12345678000199', is_active=True
        )
        
        # Estágio para Jobs
        self.job_stage = JobStage.objects.create(
            name='Modelagem', order=1
        )
        
        # Trabalho associado à produção
        self.job = Job.objects.create(
            order_number='ORD-001', client=self.client_obj, patient_name='João Silva',
            entry_date=date.today(), due_date=date.today(), 
            status='in_progress', current_stage=self.job_stage
        )
        self.job_assignment = JobAssignment.objects.create(
            job=self.job, employee=self.employee_producao, task_description='Aplicar cerâmica'
        )

        # Endpoints
        self.employees_url = reverse('employee-list')
        self.job_assignments_url = reverse('jobassignment-list')
        self.clients_url = reverse('client-list')
        self.commissions_url = reverse('commissionpayment-list')

    def test_employee_list_access_superadmin(self):
        self.client_api.force_authenticate(user=self.superadmin)
        response = self.client_api.get(self.employees_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_employee_list_access_gerente(self):
        self.client_api.force_authenticate(user=self.gerente)
        response = self.client_api.get(self.employees_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_employee_list_access_recepcao_denied(self):
        self.client_api.force_authenticate(user=self.recepcao)
        response = self.client_api.get(self.employees_url)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_email_notifications_on_profile_or_role_change(self):
        from django.core import mail
        
        # Clear outbox generated by setUp users
        mail.outbox = []
        
        user = CustomUser.objects.create_user(username="mail", email="mail@teste.com", role='producao')
        EmployeeProfile.objects.create(user=user, name="Mail Teste", position="Operador", hire_date=date.today())
        
        self.assertEqual(len(mail.outbox), 1)
        self.assertTrue('Bem-vindo' in mail.outbox[0].subject)
        
        mail.outbox = []
        
        # Update Role
        user.role = 'gerente'
        user.save()
        
        self.assertEqual(len(mail.outbox), 1)
        self.assertTrue('Alteração' in mail.outbox[0].subject)


    def test_employee_list_access_producao_denied(self):
        self.client_api.force_authenticate(user=self.producao)
        response = self.client_api.get(self.employees_url)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_job_assignment_access_producao(self):
        # Operacionais DEVEM conseguir ver tarefas de jobs (Kanban)
        self.client_api.force_authenticate(user=self.producao)
        response = self.client_api.get(self.job_assignments_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_clients_access_recepcao(self):
        # Recepção DEVE conseguir ver clientes
        self.client_api.force_authenticate(user=self.recepcao)
        response = self.client_api.get(self.clients_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_clients_access_producao_denied(self):
        # Produção NÃO DEVE conseguir ver a base de clientes inteira
        self.client_api.force_authenticate(user=self.producao)
        response = self.client_api.get(self.clients_url)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_employee_create_as_gerente(self):
        """1. POST /employees/ como gerente"""
        self.client_api.force_authenticate(user=self.gerente)
        new_user = CustomUser.objects.create_user(username='new_emp', password='123', role='producao')
        data = {
            'user': new_user.id, 
            'name': 'Novo Funcionario',
            'document_number': '12312312344',
            'department': 'Cerâmica',
            'position': 'Ceramista',
            'hire_date': str(date.today())
        }
        response = self.client_api.post(self.employees_url, data)
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['user']['id'], new_user.id)

    def test_employee_soft_delete(self):
        """2. is_active=False via PATCH + verify list"""
        self.client_api.force_authenticate(user=self.gerente)
        # Soft delete
        response = self.client_api.patch(reverse('employee-detail', args=[self.employee_producao.id]), {'is_active': False})
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        
        # Verify not in list (assuming viewset filters by is_active)
        response = self.client_api.get(self.employees_url)
        self.assertNotIn(self.employee_producao.name, [e['name'] for e in response.data.get('results', response.data)])

    def test_commission_access_gerente(self):
        """3. GET /commission-payments/ como gerente"""
        self.client_api.force_authenticate(user=self.gerente)
        response = self.client_api.get(self.commissions_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_commission_access_producao_denied(self):
        """4. GET /commission-payments/ como producao deve ser bloqueado"""
        self.client_api.force_authenticate(user=self.producao)
        response = self.client_api.get(self.commissions_url)
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

class UtilsTests(TestCase):
    """Testes para utilitários do sistema"""

    def test_xml_parser_nfe(self):
        """5. parse_nfe_xml() com XML válido"""
        from apps.materials.xml_parser import parse_nfe_xml
        import io
        
        valid_xml = """<?xml version="1.0" encoding="UTF-8"?>
        <nfeProc xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
            <NFe>
                <infNFe Id="NFe123" versao="4.00">
                    <ide>
                        <nNF>12345</nNF>
                        <dhEmi>2023-10-27T10:00:00-03:00</dhEmi>
                    </ide>
                    <emit>
                        <CNPJ>12345678000199</CNPJ>
                        <xNome>Fornecedor Teste</xNome>
                    </emit>
                    <total>
                        <ICMSTot>
                            <vNF>1500.50</vNF>
                        </ICMSTot>
                    </total>
                </infNFe>
            </NFe>
        </nfeProc>
        """
        xml_file = io.BytesIO(valid_xml.encode('utf-8'))
        result = parse_nfe_xml(xml_file)
        
        self.assertEqual(result['status'], 'sucesso')
        self.assertEqual(result['numero'], '12345')
        self.assertEqual(result['data_emissao'], '2023-10-27T10:00:00-03:00')
        self.assertEqual(result['valor_total'], '1500.50')
