# Generated by Django 4.2.28 on 2026-03-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalityPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('weekly', 'Semanal'), ('holiday', 'Feriados'), ('custom', 'Personalizado')], max_length=20, verbose_name='Tipo de Padrão')),
                ('name', models.CharField(help_text='Nome descritivo do padrão sazonal', max_length=100, verbose_name='Nome do Padrão')),
                ('description', models.TextField(help_text='Descrição detalhada do padrão', verbose_name='Descrição')),
                ('impact_factor', models.FloatField(help_text='Multiplicador do impacto (1.0 = neutro, >1.0 = positivo, <1.0 = negativo)', verbose_name='Fator de Impacto')),
                ('start_period', models.CharField(help_text='Quando o padrão começa (ex: Janeiro, Q1, Semana 1)', max_length=50, verbose_name='Período de Início')),
                ('end_period', models.CharField(help_text='Quando o padrão termina', max_length=50, verbose_name='Período de Fim')),
                ('confidence_level', models.FloatField(help_text='Confiança estatística do padrão (0-1)', verbose_name='Nível de Confiança')),
                ('historical_data', models.JSONField(default=dict, help_text='Dados históricos que suportam o padrão', verbose_name='Dados Históricos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Padrão de Sazonalidade',
                'verbose_name_plural': 'Padrões de Sazonalidade',
                'ordering': ['-confidence_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('revenue', 'Receita'), ('jobs_volume', 'Volume de Trabalhos'), ('client_acquisition', 'Aquisição de Clientes'), ('average_ticket', 'Ticket Médio'), ('production_time', 'Tempo de Produção'), ('client_satisfaction', 'Satisfação do Cliente')], max_length=30, verbose_name='Tipo de Tendência')),
                ('analysis_period_start', models.DateField(verbose_name='Início do Período')),
                ('analysis_period_end', models.DateField(verbose_name='Fim do Período')),
                ('current_value', models.FloatField(verbose_name='Valor Atual')),
                ('previous_value', models.FloatField(verbose_name='Valor Anterior')),
                ('percentage_change', models.FloatField(help_text='Mudança em relação ao período anterior', verbose_name='Mudança Percentual')),
                ('trend_strength', models.CharField(choices=[('weak', 'Fraca'), ('moderate', 'Moderada'), ('strong', 'Forte'), ('very_strong', 'Muito Forte')], max_length=20, verbose_name='Força da Tendência')),
                ('statistical_significance', models.FloatField(help_text='P-value da análise estatística', verbose_name='Significância Estatística')),
                ('insights', models.JSONField(default=list, help_text='Lista de insights gerados pela análise', verbose_name='Insights')),
                ('recommendations', models.JSONField(default=list, help_text='Recomendações baseadas na tendência', verbose_name='Recomendações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Análise de Tendência',
                'verbose_name_plural': 'Análises de Tendências',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenuePredictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semi_annual', 'Semestral'), ('annual', 'Anual')], max_length=20, verbose_name='Tipo de Período')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Receita Prevista')),
                ('confidence_score', models.FloatField(help_text='Confiança da predição (0-1)', verbose_name='Score de Confiança')),
                ('factors_analysis', models.JSONField(default=dict, help_text='Fatores que influenciam a predição', verbose_name='Análise de Fatores')),
                ('seasonality_impact', models.FloatField(default=0.0, help_text='Impacto sazonal na receita (-1 a 1)', verbose_name='Impacto da Sazonalidade')),
                ('trend_direction', models.CharField(choices=[('up', 'Crescimento'), ('stable', 'Estável'), ('down', 'Declínio')], default='stable', max_length=20, verbose_name='Direção da Tendência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Predição de Receita',
                'verbose_name_plural': 'Predições de Receita',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('revenue_drop', 'Queda de Receita'), ('capacity_overload', 'Sobrecarga de Capacidade'), ('client_churn_risk', 'Risco de Perda de Cliente'), ('seasonal_opportunity', 'Oportunidade Sazonal'), ('efficiency_decline', 'Declínio de Eficiência'), ('market_trend', 'Tendência de Mercado')], max_length=30, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('predicted_impact', models.TextField(help_text='Descrição do impacto esperado', verbose_name='Impacto Previsto')),
                ('probability', models.FloatField(help_text='Probabilidade do evento ocorrer (0-1)', verbose_name='Probabilidade')),
                ('time_horizon', models.CharField(help_text='Quando o evento pode ocorrer', max_length=50, verbose_name='Horizonte Temporal')),
                ('recommended_actions', models.JSONField(default=list, help_text='Lista de ações recomendadas', verbose_name='Ações Recomendadas')),
                ('related_metrics', models.JSONField(default=dict, help_text='Métricas que geraram o alerta', verbose_name='Métricas Relacionadas')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reconhecido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconhecido por')),
            ],
            options={
                'verbose_name': 'Alerta Preditivo',
                'verbose_name_plural': 'Alertas Preditivos',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('daily_revenue', 'Receita Diária'), ('jobs_completed', 'Trabalhos Concluídos'), ('avg_production_time', 'Tempo Médio de Produção'), ('client_satisfaction', 'Satisfação do Cliente'), ('technician_efficiency', 'Eficiência dos Técnicos'), ('bottleneck_incidents', 'Incidentes de Gargalo'), ('on_time_delivery', 'Entregas no Prazo'), ('rework_rate', 'Taxa de Retrabalho')], max_length=30, verbose_name='Tipo de Métrica')),
                ('date', models.DateField(verbose_name='Data')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('target_value', models.FloatField(blank=True, help_text='Meta estabelecida para esta métrica', null=True, verbose_name='Valor Meta')),
                ('variance_from_target', models.FloatField(blank=True, help_text='Diferença percentual da meta', null=True, verbose_name='Variação da Meta')),
                ('benchmark_value', models.FloatField(blank=True, help_text='Valor de referência do mercado', null=True, verbose_name='Valor de Benchmark')),
                ('notes', models.TextField(blank=True, help_text='Observações sobre a métrica', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Métrica de Performance',
                'verbose_name_plural': 'Métricas de Performance',
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('revenue_chart', 'Gráfico de Receita'), ('jobs_metrics', 'Métricas de Trabalhos'), ('trend_analysis', 'Análise de Tendências'), ('performance_kpi', 'KPIs de Performance'), ('predictive_alerts', 'Alertas Preditivos'), ('seasonality_view', 'Visualização de Sazonalidade'), ('client_insights', 'Insights de Clientes'), ('efficiency_tracker', 'Rastreador de Eficiência')], max_length=30, verbose_name='Tipo de Widget')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posição X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posição Y')),
                ('width', models.IntegerField(default=4, verbose_name='Largura')),
                ('height', models.IntegerField(default=3, verbose_name='Altura')),
                ('configuration', models.JSONField(default=dict, help_text='Configurações específicas do widget', verbose_name='Configuração')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalo de Atualização (segundos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Widget do Dashboard',
                'verbose_name_plural': 'Widgets do Dashboard',
                'ordering': ['position_y', 'position_x'],
            },
        ),
    ]
