# Generated by Django 4.2.28 on 2026-03-14 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialties', models.JSONField(default=list, help_text='Lista de tipos de prótese que o técnico domina', verbose_name='Especialidades')),
                ('skill_level', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Expert')], default=2, verbose_name='Nível de Habilidade')),
                ('average_work_time', models.FloatField(default=8.0, help_text='Horas médias de trabalho por dia', verbose_name='Tempo Médio de Trabalho (horas)')),
                ('efficiency_rating', models.FloatField(default=1.0, help_text='Multiplicador de eficiência (1.0 = normal, >1.0 = mais eficiente)', verbose_name='Rating de Eficiência')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Técnico',
                'verbose_name_plural': 'Perfis de Técnicos',
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Estimada de Início')),
                ('estimated_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Estimada de Conclusão')),
                ('estimated_duration_hours', models.FloatField(blank=True, null=True, verbose_name='Duração Estimada (horas)')),
                ('priority_score', models.FloatField(default=0.0, help_text='Score calculado para priorização (maior = mais prioritário)', verbose_name='Score de Prioridade')),
                ('bottleneck_risk', models.FloatField(default=0.0, help_text='Probabilidade de causar gargalo (0-1)', verbose_name='Risco de Gargalo')),
                ('optimization_notes', models.TextField(blank=True, help_text='Observações do algoritmo de otimização', verbose_name='Notas de Otimização')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='intelligent_scheduling.technicianprofile', verbose_name='Técnico Designado')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='jobs.job', verbose_name='Trabalho')),
            ],
            options={
                'verbose_name': 'Cronograma de Produção',
                'verbose_name_plural': 'Cronogramas de Produção',
                'ordering': ['-priority_score', 'estimated_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MLModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Nome identificador do modelo ML', max_length=100, verbose_name='Nome do Modelo')),
                ('model_version', models.CharField(default='1.0', max_length=50, verbose_name='Versão do Modelo')),
                ('accuracy_score', models.FloatField(blank=True, null=True, verbose_name='Score de Acurácia')),
                ('mae_score', models.FloatField(blank=True, null=True, verbose_name='Mean Absolute Error')),
                ('rmse_score', models.FloatField(blank=True, null=True, verbose_name='Root Mean Square Error')),
                ('training_data_size', models.IntegerField(default=0, verbose_name='Tamanho dos Dados de Treino')),
                ('last_trained_at', models.DateTimeField(auto_now_add=True, verbose_name='Último Treino')),
                ('feature_importance', models.JSONField(default=dict, help_text='Importância de cada feature no modelo', verbose_name='Importância das Features')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Métricas do Modelo ML',
                'verbose_name_plural': 'Métricas dos Modelos ML',
                'unique_together': {('model_name', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='JobTimeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosthesis_type', models.CharField(help_text='Tipo específico de prótese', max_length=100, verbose_name='Tipo de Prótese')),
                ('material', models.CharField(blank=True, help_text='Material utilizado', max_length=100, verbose_name='Material')),
                ('complexity_level', models.IntegerField(choices=[(1, 'Simples'), (2, 'Médio'), (3, 'Complexo'), (4, 'Muito Complexo')], default=2, verbose_name='Nível de Complexidade')),
                ('base_time_hours', models.FloatField(help_text='Tempo base estimado em horas', verbose_name='Tempo Base (horas)')),
                ('min_time_hours', models.FloatField(help_text='Tempo mínimo possível', verbose_name='Tempo Mínimo (horas)')),
                ('max_time_hours', models.FloatField(help_text='Tempo máximo esperado', verbose_name='Tempo Máximo (horas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Estimativa de Tempo',
                'verbose_name_plural': 'Estimativas de Tempo',
                'unique_together': {('prosthesis_type', 'material', 'complexity_level')},
            },
        ),
        migrations.CreateModel(
            name='BottleneckAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('tech_overload', 'Sobrecarga de Técnico'), ('deadline_risk', 'Risco de Prazo'), ('resource_conflict', 'Conflito de Recursos'), ('capacity_exceeded', 'Capacidade Excedida')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('suggested_actions', models.JSONField(default=list, help_text='Lista de ações sugeridas para resolver o gargalo', verbose_name='Ações Sugeridas')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('affected_jobs', models.ManyToManyField(blank=True, related_name='bottleneck_alerts', to='jobs.job', verbose_name='Trabalhos Afetados')),
                ('affected_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='intelligent_scheduling.technicianprofile', verbose_name='Técnico Afetado')),
            ],
            options={
                'verbose_name': 'Alerta de Gargalo',
                'verbose_name_plural': 'Alertas de Gargalos',
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
