# Generated by Django 5.2.1 on 2025-06-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('document_type', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4, null=True, verbose_name='Document Type')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Document Number')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_primary', models.CharField(max_length=20, verbose_name='Primary Phone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Secondary Phone')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complement')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Neighborhood')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('address_zip_code', models.CharField(blank=True, max_length=10, verbose_name='ZIP Code')),
                ('technical_preferences', models.TextField(blank=True, verbose_name='Technical Preferences')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
