# Generated by Django 5.2.3 on 2025-06-14 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address_street', models.CharField(max_length=255, verbose_name='Rua')),
                ('address_number', models.CharField(max_length=20, verbose_name='Número')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('address_neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('address_city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(max_length=2, verbose_name='Estado')),
                ('address_zip_code', models.CharField(max_length=10, verbose_name='CEP')),
                ('employee_type', models.CharField(choices=[('technician', 'Técnico em Prótese'), ('assistant', 'Auxiliar'), ('receptionist', 'Recepcionista'), ('manager', 'Gerente'), ('owner', 'Proprietário'), ('other', 'Outro')], max_length=20, verbose_name='Tipo de Funcionário')),
                ('contract_type', models.CharField(choices=[('clt', 'CLT'), ('freelancer', 'Freelancer'), ('intern', 'Estagiário'), ('partner', 'Sócio')], max_length=20, verbose_name='Tipo de Contrato')),
                ('hire_date', models.DateField(verbose_name='Data de Admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salário Base')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Transporte')),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Refeição')),
                ('health_insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Plano de Saúde')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('bank_agency', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly_closing', 'Fechamento Mensal'), ('annual_balance', 'Balanço Anual'), ('cash_flow', 'Fluxo de Caixa'), ('profit_loss', 'DRE - Demonstração de Resultado')], max_length=20, verbose_name='Tipo de Relatório')),
                ('start_date', models.DateField(verbose_name='Data Início')),
                ('end_date', models.DateField(verbose_name='Data Fim')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Mês')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Receita Total')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Despesas Totais')),
                ('payroll_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Despesas com Folha')),
                ('operational_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Despesas Operacionais')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Lucro Líquido')),
                ('total_jobs', models.IntegerField(default=0, verbose_name='Total de Trabalhos')),
                ('completed_jobs', models.IntegerField(default=0, verbose_name='Trabalhos Concluídos')),
                ('pending_jobs', models.IntegerField(default=0, verbose_name='Trabalhos Pendentes')),
                ('report_data', models.JSONField(default=dict, help_text='Dados detalhados do relatório em formato JSON', verbose_name='Dados do Relatório')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
            ],
            options={
                'verbose_name': 'Relatório Financeiro',
                'verbose_name_plural': 'Relatórios Financeiros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('month', models.IntegerField(verbose_name='Mês')),
                ('reference_date', models.DateField(verbose_name='Data de Referência')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechada')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fechada em')),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Salário Bruto')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Descontos')),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Salário Líquido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='Fechada por')),
            ],
            options={
                'verbose_name': 'Período de Folha',
                'verbose_name_plural': 'Períodos de Folha',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Base')),
                ('worked_days', models.IntegerField(default=30, verbose_name='Dias Trabalhados')),
                ('worked_hours', models.DecimalField(decimal_places=2, default=Decimal('220.00'), max_digits=6, verbose_name='Horas Trabalhadas')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Horas Extras')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Horas Extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Bonificação')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comissão')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Transporte')),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Vale Refeição')),
                ('inss_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto INSS')),
                ('irrf_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto IRRF')),
                ('health_insurance_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Desconto Plano de Saúde')),
                ('other_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Outros Descontos')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salário Bruto')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Descontos')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Salário Líquido')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='payroll.employee', verbose_name='Funcionário')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Entrada de Folha',
                'verbose_name_plural': 'Entradas de Folha',
                'ordering': ['employee__full_name'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
