# Generated by Django 5.2.3 on 2025-06-14 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificador do comando', max_length=100, unique=True, verbose_name='Nome do Comando')),
                ('description', models.TextField(help_text='Descrição do que o comando faz', verbose_name='Descrição')),
                ('keywords', models.JSONField(help_text='Lista de palavras-chave que ativam este comando', verbose_name='Palavras-chave')),
                ('function_name', models.CharField(help_text='Nome da função Python que executa o comando', max_length=100, verbose_name='Nome da Função')),
                ('required_permissions', models.JSONField(default=list, help_text='Lista de permissões necessárias para executar o comando', verbose_name='Permissões Necessárias')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Comando de IA',
                'verbose_name_plural': 'Comandos de IA',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Identificador único da sessão de chat', max_length=100, unique=True, verbose_name='ID da Sessão')),
                ('title', models.CharField(blank=True, help_text='Título da conversa baseado no primeiro comando', max_length=200, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão de Chat',
                'verbose_name_plural': 'Sessões de Chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=10, verbose_name='Tipo de Mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('command_executed', models.CharField(blank=True, help_text='Comando do sistema que foi executado', max_length=100, null=True, verbose_name='Comando Executado')),
                ('execution_result', models.JSONField(blank=True, help_text='Dados retornados pela execução do comando', null=True, verbose_name='Resultado da Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Mensagem de Chat',
                'verbose_name_plural': 'Mensagens de Chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Comando original digitado pelo usuário', verbose_name='Texto de Entrada')),
                ('status', models.CharField(choices=[('success', 'Sucesso'), ('error', 'Erro'), ('permission_denied', 'Permissão Negada')], max_length=20, verbose_name='Status')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='Dados do Resultado')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('execution_time', models.FloatField(help_text='Tempo em segundos para executar o comando', verbose_name='Tempo de Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Executado em')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ai_assistant.aicommand', verbose_name='Comando')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ai_assistant.chatmessage', verbose_name='Mensagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_executions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Execução de Comando',
                'verbose_name_plural': 'Execuções de Comando',
                'ordering': ['-created_at'],
            },
        ),
    ]
