# Generated by Django 4.2.28 on 2026-03-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_payroll_fields'),
        ('payroll', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollentry',
            options={'ordering': ['employee__name'], 'verbose_name': 'Entrada de Folha', 'verbose_name_plural': 'Entradas de Folha'},
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='report_data',
            field=models.JSONField(default=dict, verbose_name='Dados do Relatório'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='employees.employeeprofile', verbose_name='Funcionário'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
