# Generated by Django 4.2.28 on 2026-03-12 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated at')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('start_period', models.DateField(verbose_name='Start Period')),
                ('end_period', models.DateField(verbose_name='End Period')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Commission Payment',
                'verbose_name_plural': 'Commission Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('document_number', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('address_complement', models.CharField(blank=True, max_length=100, verbose_name='Complement')),
                ('address_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Neighborhood')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('address_zip_code', models.CharField(blank=True, max_length=10, verbose_name='ZIP Code')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Termination Date')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of job value that employee receives as commission', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission Percentage')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank Name')),
                ('bank_branch', models.CharField(blank=True, max_length=20, verbose_name='Bank Branch')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Bank Account')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated at')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Assigned Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('task_description', models.CharField(max_length=255, verbose_name='Task Description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Completion Notes')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override default commission percentage if needed', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Commission Percentage')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='employees.employeeprofile', verbose_name='Employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.job', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Job Assignment',
                'verbose_name_plural': 'Job Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('job_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='employees.jobassignment', verbose_name='Job Assignment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.commissionpayment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Commission Payment Item',
                'verbose_name_plural': 'Commission Payment Items',
            },
        ),
        migrations.AddField(
            model_name='commissionpayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to='employees.employeeprofile', verbose_name='Employee'),
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was created', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the record was last updated', verbose_name='Updated at')),
                ('skill_name', models.CharField(max_length=100, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('proficiency_level', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1, verbose_name='Proficiency Level')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employeeprofile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'unique_together': {('employee', 'skill_name')},
            },
        ),
    ]
