# Generated by Django 5.2.3 on 2025-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price_adjustment_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Percentage adjustment for this client's prices. Positive for markup, negative for discount.", max_digits=5, verbose_name='Price Adjustment (%)'),
        ),
    ]
